### ISSUE TITLE
Add support for xls, docs, pdf etc

### ISSUE THREAD

**Issue by sdmydbr9** [danvergara/morphos#39]
Add support for converting docs to pdf, xls to csv and other formats as well. 
this is very commonly used online

**Comment by danvergara** [comment]
PDF -DOCX was added in [v0.2.0](https://github.com/danvergara/morphos/releases/tag/v0.2.0). Don't know if we need to cover DOC specifically. If so, let me know. Otherwise, I can start working on XLSX to CSV, rn.

**Comment by sdmydbr9** [comment]
Thanks for adding the pdf to docx, im sure many will appreciate this feature, although the xls to csv has much less use cases, adding it will make this more dynamic imo...

**Comment by mkalus** [comment]
Since you are using LibreOffice for conversion, why not support ODT, too?

**Comment by danvergara** [comment]
Nobody asked for it before.
