### ISSUE TITLE
Support for batch conversion

### ISSUE THREAD

**Issue by bobvmierlo** [danvergara/morphos#42]
**Describe the solution you'd like**
Would love to see this tool being able to do batch conversions of files. In my example, batch convert about 100 PDF files to DOCX.

**Comment by danvergara** [comment]
Thanks for bringing this to my attention.
This is something that I'm still planning out. Can you tell me more about your use case?

**Comment by bobvmierlo** [comment]
Mainly for work where we regularly need to import batches of files. In the last case there were over 300 PDF files that we needed to convert to docx.

**Comment by danvergara** [comment]
That sounds like a premium-business feature that I won't fully cover anytime soon, not until I cover the most common file conversions. Feel free to abstract out the logic behind PDF-DOCX conversion and embed it into your own solution.

Sorry.
