### ISSUE TITLE
Performance when converting PDF to JPG images

### ISSUE THREAD

**Issue by anhgeeky** [danvergara/morphos#45]
**Describe the bug**
When I convert PDF to JPG images.
The PDF file has 106 pages (~8MB)

**Expected behavior**
I tried changing `github.com/unidoc/unipdf` to `github.com/gen2brain/go-fitz`
Performance is clearly improved
**unipdf/v3**: 4m42.8998436s
**go-fitz**: 47.2890154s

**Desktop (please complete the following information):**
OS Name	Microsoft Windows 11 Pro
Version	10.0.22000 Build 22000
System Type	x64-based PC
Processor	Intel(R) Xeon(R) CPU E5-2696 v3 @ 2.30GHz, 2301 Mhz, 18 Core(s), 36 Logical Processor(s)
Installed Physical Memory (RAM)	64.0 GB

**Comment by danvergara** [comment]
I just replaced unipdf as you suggested @anhgeeky.

Care to QA this PR, please?

https://github.com/danvergara/morphos/pull/46

**Comment by tranminhbinhit** [comment]
Good idea
