### ISSUE TITLE
how about an API to integrate with other services?

### ISSUE THREAD

**Issue by cerokool32** [danvergara/morphos#50]
**Is your feature request related to a problem? Please describe.**
I am currently developing a personalized statistics dashboard, and it would be beneficial to have a service that can convert these reports into various formats, such as docx to pdf. It would also be helpful if this service could handle data ingestion by converting xlsx to csv in some cases.

**Describe the solution you'd like**
An easy way would be to have just 2 endpoints:
- GET '/formats' to get the available formats the file can be converted to
- POST '/to/{format}' to transform the file into the specified format

**Describe alternatives you've considered**
My actual position was to integrate Apache POI into the microservice and deal with all the complexities while handling xlsx files, while docx reports are still on dev because of issues while dealing with some images.

**Additional context**
I think this is simple and concise but always open to ideas and discussion.

**Comment by websvcPT** [comment]
+1 on this
Unfortunately can't help with Golang, but happy to help testing the API

**Comment by ajtatum** [comment]
I would love to see this as it would allow the possibility to create a Chrome extension to right click on a webp and save it as a PNG. There's already an extension to do this, but it relies on third party services.
