### ISSUE TITLE
Add Dark Mode theme

### ISSUE THREAD

**Issue by HypnoticPenguin** [danvergara/morphos#51]
I like Morphos, its an excellent tool however an option to select a dark mode theme would be really useful as the current UI is very bright!  Either have an configurable environment variable which can be setup in docker or a toggle button in the top right of the screen to switch between light and dark mode.

**Comment by danvergara** [comment]
Hi @mmozzano!

This is addressed in #58. Please feel free to review it and let me know if that resolves the problem.

**Comment by danvergara** [comment]
@mmozzano  new images are released on Git tags. I'll cut a release tonight.

**Comment by danvergara** [comment]
Morphos [v0.4.0](https://github.com/danvergara/morphos/releases/tag/v0.4.0) is out!
